import groovy.json.JsonSlurper

pipeline {
         agent any
            environment {
                    pastaprojeto = "GRPSINERGY"
                    pastaaplicacao = "Pine.IntegracaoSinergyRH.Job"
                    repoName = "npm-jobs"
                    version = "1.22723"
            }
            stages {                  
                stage('MyStage') {
                    steps {
                    ansibleTower(
                        towerServer: 'Ansible Tower',
                        towerCredentialsId: '',
                        templateType: 'job',
                        jobTemplate: 'Esteira-Jobs',
                        inventory: '',
                        jobTags: '',
                        skipJobTags: '',
                        limit: '',
                        removeColor: false,
                        verbose: true,
                        credential: '',
                        extraVars: '''---
                pastaprojeto: "${pastaprojeto}"
                pastaaplicacao: "${pastaaplicacao}"
                reponame: "${repoName}"
                versionpacote: "${version}"
                ''',
                        async: false
        )

        }

                }
					
        }
}