apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: wordpress-pine
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/requester: system:serviceaccounts:cicd:jenkins
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    nodeSelector: null
    output:
      imageLabels:
      - name: io.k8s.display-name
        value: WordPress
      - name: io.k8s.description
        value: WordPress application and S2I builder.
      - name: io.openshift.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.openshift.tags
        value: builder,php,wordpress

    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGESTREAM}
        namespace: ${NAMESPACE}-dev
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${BRANCHNAME}
        uri: ${GITURLBUILD}
      secrets:
      - destinationDir: /etc/pki/tls/certs
        secret:
          name: trust-capine
      sourceSecret:
        name: svc135tfs
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 5c8db620bd214787
      type: GitHub
    - generic:
        secret: 109f637bbe82ab9a
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
parameters:
  - name: NAME 
    required: true 
  - name: IMAGESTREAM 
    required: true 
  - name: NAMESPACE
    required: true
  - name: BRANCHNAME
    required: true
  - name: GITURLBUILD
    required: true