apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: dotnetcore-pine
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/requester: system:serviceaccounts:cicd:jenkins
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGESTREAM}
        namespace: ${NAMESPACE}-dev
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${BRANCHNAME}
        uri: ${GITURLBUILD}
      secrets:
      - destinationDir: /etc/pki/tls/certs
        secret:
          name: trust-capine
      sourceSecret:
        name: svc135tfs
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: DOTNET_RESTORE_SOURCES
          value: http://artifactory.hml.pine.com/artifactory/api/nuget/pine-nuget
        - name: DOTNET_STARTUP_PROJECT
          value: ${SOLUTIONFILE}
        from:
          kind: ImageStreamTag
          name: dotnet:2.1
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 5c8db620bd214787
      type: GitHub
    - generic:
        secret: 109f637bbe82ab9a
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
parameters:
  - name: NAME 
    required: true 
  - name: IMAGESTREAM 
    required: true 
  - name: NAMESPACE
    required: true
  - name: BRANCHNAME
    required: true
  - name: GITURLBUILD
    required: true
  - name: SOLUTIONFILE
    required: true
